# Generated by Django 5.1.6 on 2025-03-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casaKolor1', '0003_pedido_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='presentacion',
            field=models.CharField(choices=[('cuarto', '1/4 de Galón'), ('1 galon', '1 Galón'), ('dos_cinco', '2.5 Galones'), ('cinco', '5 Galones (Caneca)')], default='galon', max_length=20),
        ),
    ]
