# Generated by Django 5.1.7 on 2025-03-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casaKolor1', '0004_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='presentacion',
            field=models.CharField(choices=[('cuarto', '1/4 de Galon'), ('galon', 'Galon'), ('dos_cinco', '2.5 Galones'), ('cinco', '5 Galones (Caneca)')], default='galon', max_length=20),
        ),
    ]
