# Generated by Django 5.1.4 on 2025-02-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casaKolor1', '0005_alter_productos_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('herramientas', 'Herramientas'), ('pinturas', 'Pinturas')], default='herramientas', max_length=20),
        ),
    ]
