# Generated by Django 5.1.4 on 2025-02-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casaKolor1', '0006_productos_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
    ]
