# Generated by Django 5.1.4 on 2025-02-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casaKolor1', '0009_sugerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='presentacion',
            field=models.CharField(choices=[('cuarto', '1/4 de Galón'), ('galon', 'Galón'), ('dos_cinco', '2.5 Galones'), ('cinco', '5 Galones (Caneca)')], default='galon', max_length=20),
        ),
    ]
