# Generated by Django 5.1.4 on 2025-02-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casaKolor1', '0013_remove_factura_cliente_alter_productos_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
